name: Fetch latest blog posts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: pip caches
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Update README
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |-
        python blog_posts.py
        cat README.md
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "contact@aaronluna.dev"
        git config --global user.name "Aaron Luna"
        git add -A
        git commit -m "Update blog posts" || exit 0
        git push
